### ISSUE TITLE
^ and < keys are swapped for Windows 10 using an Apple Magic Keyboard

### ISSUE THREAD

**Issue by johannesstroebele91** [christian-korneck/win10-keyboard-macbook-german#1]
A normal Windows 10 installation is used (no bootcamp or similar). Still both ^ and < are swapped. Could you please create a separat release? Probably more people using a normal installation could have this issue. My use case is that I use a Macbook and a Windows PC and I want to have the same Mac keyboard layout for both of them using my Apple Magic Keyboard.

**Comment by christian-korneck** [comment]
hi @johannesstroebele91 I did a quick hack and switched the two keys. Source and installer are attached. I'm not entirely sure this will work, but couldn't test. If it doesn't give you the correct result you may need to edit with MS Keyboard layout creator. 

https://download.microsoft.com/download/6/f/5/6f5ce43a-e892-4fd1-b9a6-1a0cbb64e6e2/MSKLC.exe

You may need to activate the optional .NET3 feature in Win10 to be able to install it:

```
Enable-WindowsOptionalFeature -Online -FeatureName "NetFx3" -All
```


[DeApplC1.klc.txt](https://github.com/christian-korneck/win10-keyboard-macbook-german/files/6340658/DeApplC1.klc.txt)
[deapplc1.zip](https://github.com/christian-korneck/win10-keyboard-macbook-german/files/6340659/deapplc1.zip)

**Comment by johannesstroebele91** [comment]
Just perfect, your installer worked! Thank you and have a great day. PS maybe it would be great to offer it as a separate release?

**Comment by johannesstroebele91** [comment]
Just perfect, your installer worked! Thank you and have a great day. PS maybe it would be great to offer it as a separate release?

**Comment by christian-korneck** [comment]
thanks for the feedback, linked to it in the readme
