### ISSUE TITLE
Fork because of German Swiss (Slightly different layout)

### ISSUE THREAD

**Issue by DennyWeinberg** [christian-korneck/win10-keyboard-macbook-german#3]
Hi, I created a fork for my keyboard, which is slightly different.
See https://github.com/DennyWeinberg/win10-keyboard-macbook-german.
I prepared everything, I will push the final layout tomorrow.

Feel free to mention it in your README :)

Denny

**Comment by christian-korneck** [comment]
thanks for sharing! I’ve added a link in the README.
